[app]
    host            = "127.0.0.1:8000"

[configDB]
    host            = "127.0.0.1"
    port            = 32768
    user            = "postgres"
    password        = "password"
    dbname          = "go-postgres"

[api]
    secret_key      = "sapiperahhijau"

[expired]
    hours           = "0"
    minutes         = "10"